### PR TITLE
Nested file detection

### PR DESCRIPTION
**Pull request by cgc**
When merging this, can you also enable travis CI support for the repo as well? https://travis-ci.org/scitran/utilities

### CODE REVIEW

**Comment by cgc** [comment]
I don't think this supports nested files in output. My latest change to [realign-unwarp](https://github.com/scitran-apps/realign-unwarp/commit/bd40f9653dc979786348e9ad52d11eadcd9ece05) doesn't seem to fix things in my test instance. poking around in mongo, the analysis on the session also don't have the outputs.

Taking a step back, I'm trying to get files in folders in the output directory into the analysis output. So if my output directory has `logs/file.log`,  I want that to (short-term) show up in the API and (long-term) show up in the UI.

cc @ryansanford

**Comment by ryansanford** [comment]
@kofalt Can you comment on directories in the `output` folder for gear results? I don't see mention of intended support/behavior one way or the other.

**Comment by kofalt** [comment]
Right now, the engine will walk the output folder (and any contents of subfolders) and mark each file for upload. There is no mention of this in the spec because I couldn't envision a use case for it - gears inherently are not informed of the hierarchy and each container is "flat" in that attached files do not have a tree to them. My expectation is that the scitran upload endpoint will ignore all but the last segment of a uploaded file's path.

So I'm not sure what the point of having folders in a gear output would be? Is this just because a pre-gear algorithm lays things out that way & it's easier to leave it be that to flatten out beforehand?

**Comment by cgc** [comment]
yes, Nipype (a pipeline execution library in python) lays things out in
folders by default, which i'd prefer to support.

however, after changing .metadata.json generation to walk files in
directories, i'm still not seeing the results in the database or the UI, so
how can i 'docker exec' into engine to confirm what it is doing?

**Comment by kofalt** [comment]
Do you have access to the docker logs? You can watch those when you queue a job, you should see `Saving <filename>` as it discovers files to upload. Let me know if that doesn't seem to be working - if you want upload a gist of the logs and we can have a look.

Could you show us an example of the metadata? If this becomes troublesome I could whip up a gear that produces nested files for testing. If there's an issue it should be pretty easy to fix on our end.

**Comment by cgc** [comment]
looking at the logs for engine, it seems like my gear just isn't running correctly (cause is ENV statements not executing in runc, which I've been warned about), so it seems like that's the immediate problem, will fix that and check in with my results.

Do we have any plan to show exit code or stdout/stderr in flywheel UI? even `success` vs `error` would be a bit more helpful, but I doubt folks without ssh access could make much progress on gear development without access to stdout/stderr (an alternative to stdout/stderr access might be better documenting how the docker images are run so that folks can know they're running their images nearly identically to how engine does. While the empty environment is documented, I'm not very sure how I would test that locally)

**Comment by kofalt** [comment]
Totally, saving output has been on my radar for awhile, frankly we should already have that :) Stay tuned.

Regarding exit code, we currently have an issue in the core (https://github.com/scitran/core/issues/364) that has blocked us from returning that to the core - we currently ignore it due to an issue with a dicom QA gear. I'll bring that up again with @gsfr to see if we can get that limitation removed.

**Comment by cgc** [comment]
ok, this PR is ready for merging, it works for my realign-unwarp tests, @ryansanford !

**Pull request merged**
